[package]
name = "ron"
version = "0.1.0"
edition = "2018"

[build-dependencies]
cc = "*"

[dependencies]
packed_struct = {version = "0.10", default-features = false}

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

