[package]
name = "rlibc-sys"
version = "0.1.0"
edition = "2021"

[dependencies]

[lib]
path = "../src/lib.rs"
crate-type = ["staticlib"]

[features]
default = ["used-as-system-library"]
used-as-system-library = []
