# Configure library to be used by Rust ( in the system or in the outside it (a.k.a in kernel) )
[package]
name = "rlibc"
version = "0.1.0"
edition = "2021"

[dependencies]

[lib]
crate-type = ["lib"]

[features]
default = ["nostartfiles"]
nostartfiles = []
